//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotnetToolset.Patterns.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Literals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Literals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DotnetToolset.Patterns.Resources.Literals", typeof(Literals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The entity provided did not validate: {0}.
        /// </summary>
        internal static string p_EntityNotValid {
            get {
                return ResourceManager.GetString("p_EntityNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred when adding a DTO list of type {0}.
        /// </summary>
        internal static string p_ErrorAddingDtoListOfTypeX {
            get {
                return ResourceManager.GetString("p_ErrorAddingDtoListOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has ocurred when adding a DTO of type {0}.
        /// </summary>
        internal static string p_ErrorAddingDtoOfTypeX {
            get {
                return ResourceManager.GetString("p_ErrorAddingDtoOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred when deleting a DTO of type {0}.
        /// </summary>
        internal static string p_ErrorDeletingDtoOfTypeX {
            get {
                return ResourceManager.GetString("p_ErrorDeletingDtoOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred when editing a DTO of type {0}.
        /// </summary>
        internal static string p_ErrorEditingDtoOfTypeX {
            get {
                return ResourceManager.GetString("p_ErrorEditingDtoOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred when getting a DTO of type {0}.
        /// </summary>
        internal static string p_ErrorGettingDtoOfTypeX {
            get {
                return ResourceManager.GetString("p_ErrorGettingDtoOfTypeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range rule did not pass since its value is not ant integer.
        /// </summary>
        internal static string p_RuleIsIntegerNotPassed {
            get {
                return ResourceManager.GetString("p_RuleIsIntegerNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not null rule did not pass since its value is null.
        /// </summary>
        internal static string p_RuleIsNotNullNotPassed {
            get {
                return ResourceManager.GetString("p_RuleIsNotNullNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length rule did not pass for data &quot;{0}&quot; since its value is longer than {1}.
        /// </summary>
        internal static string p_RuleLengthNotPassed {
            get {
                return ResourceManager.GetString("p_RuleLengthNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max rule did not pass for data &quot;{0}&quot; since its value is not lower or equal to {1}.
        /// </summary>
        internal static string p_RuleMaxNotPassed {
            get {
                return ResourceManager.GetString("p_RuleMaxNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min rule did not pass for data &quot;{0}&quot; since its value is not greater or equal to {1}.
        /// </summary>
        internal static string p_RuleMinNotPassed {
            get {
                return ResourceManager.GetString("p_RuleMinNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range rule did not pass for data &quot;{0}&quot; since its value is not between {1} and {2}.
        /// </summary>
        internal static string p_RuleRangeNotPassed {
            get {
                return ResourceManager.GetString("p_RuleRangeNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx rule did not pass for data &quot;{0}&quot; since does not match with the expression {1}.
        /// </summary>
        internal static string p_RuleRegexNotPassed {
            get {
                return ResourceManager.GetString("p_RuleRegexNotPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RegEx rule was skkipped for data &quot;{0}&quot; as requested.
        /// </summary>
        internal static string p_RuleRegexSkipped {
            get {
                return ResourceManager.GetString("p_RuleRegexSkipped", resourceCulture);
            }
        }
    }
}
